# Generated by Django 5.0 on 2023-12-30 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.userprofile'),
        ),
    ]
