# Generated by Django 5.0 on 2023-12-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_usersfirendslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersfirendslist',
            name='friends',
            field=models.ManyToManyField(blank=True, to='rest_api.userprofile'),
        ),
    ]
